include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports
    - prefer_const_constructors
    - avoid_print
    - unnecessary_null_checks
    - prefer_final_fields
    - always_declare_return_types